version: '3.8'

networks:
  dev_net:
    external: true

services:
  # ---- PostgreSQL ----
  db:
    build:
      context: ./deploy/postgres
      dockerfile: Dockerfile
    container_name: gohub_postgres
    environment:
      POSTGRES_USER: gohub
      POSTGRES_PASSWORD: gohub
      POSTGRES_DB: gohub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deploy/postgres/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - dev_net

  # ---- Postgres Exporter ----
  db_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: gohub_db_exporter
    depends_on:
      - db
    environment:
      # строка подключения к базе
      DATA_SOURCE_NAME: postgres://gohub:gohub@db:5432/gohub?sslmode=disable
    ports:
      - "9187:9187"
    restart: unless-stopped
    networks:
      - dev_net

  # ---- gRPC Go Server ----
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gohub_server
    ports:
      - "50051:50051"  # gRPC
      - "8080:8080"    # HTTP/WebSocket
      - "2112:2112"    # Port for Prometheus metrics
    env_file:
      - ./.env
    environment:
      # переменные окружения для подключения к базе, можем переопределить в .env
      DATABASE__HOST: "db"
      DATABASE__PORT: "5432"
      DATABASE__USER: "gohub"
      DATABASE__PASSWORD: "gohub"
      DATABASE__DBNAME: "gohub"
    restart: unless-stopped
    networks:
      - dev_net

  # ---- Prometheus ----
  prometheus:
    image: prom/prometheus:latest
    container_name: gohub_prometheus
    depends_on:
      - server
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - dev_net

  # ---- Grafana ----
  grafana:
    image: grafana/grafana:latest
    container_name: gohub_grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - dev_net

  # ---- React ----
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: gohub_web
    depends_on:
      - server
    environment:
      # REACT_APP_WS_URL укажем на "server:8080/ws" - сетевое имя gRPC-сервера
      REACT_APP_WS_URL: ws://server:8080/ws
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - dev_net

volumes:
  postgres_data:
  grafana_data:
