global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'go_server'
    static_configs:
      - targets: ['server:2112']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['db_exporter:9187']

