name: Build Agent

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build agent
      run: go build -o agent.run cmd/agent/main.go
      
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: agent
        path: agent.run